host: 127.0.0.1
port: 8000
is_test: false

es:  # elasticsearch
  host: 'http://elastic:changeme@localhost:9200'
  indexes:
    realty: 'parser_index'
    system: 'parser_system_index'

headers:
  User-Agent: "User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) \
              Gecko/20100101 Firefox/68.0"

data_source:
  upd_timeout:  3600
  item_url: "https://dom.ria.com/node/searchEngine/v2/view/realty/{realty_id}?lang_id=2"
  list_url: "https://dom.ria.com/node/searchEngine/v2/?category=1&realty_type=2&\
            operation_type=3&fullCategoryOperation=1_2_3&page={page}&state_id=10&\
            city_id=10&limit=100&sort=inspected_sort&date_from={date_from}"

districts:
  0:  'Борщаговка'
  1:  'Голосеевский'
  2:  'Дарницкий'
  3:  'Деснянский'
  4:  'Днепровский'
  5:  'Оболонский'
  6:  'Печерский'
  7:  'Подольский'
  8:  'Святошинский'
  9:  'Соломенский'
  10: 'Троещина'
  11: 'Шевченковский'